name: Node CI/CD

on:
  push:

jobs:     
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  release:
    needs: build
    runs-on: ubuntu-latest
    uses: wizard-whitebeard/.github/workflows/callable-release.yml@main ## TODO: pass published package name as an input
