# This is a basic workflow to help you get started with Actions

name: Test Actions

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:     
  int-action-same-org:
    runs-on: self-hosted
    
    steps:
      - name: 'Execute action in internal repo'
        uses: bugbash/jens-internal-action@master

  int-action-different-org:
    runs-on: self-hosted
    
    steps:
      - name: 'Execute action in internal repo in another org'
        uses: jenschelkopf/internal-action@master

  private-action-different-org:
    runs-on: self-hosted
    
    steps:
      - name: 'Execute action in internal repo in another org'
        uses: jenschelkopf/private-action@master
