name: Release
on: [workflow_call]

jobs:
  deploy_to_review:
    name: Deploy Review
    runs-on: review-runner
    if: github.event_name == 'pull_request'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  deploy_to_staging:
    name: Deploy Staging
    runs-on: staging-runner
    if: github.event.ref == 'refs/heads/main'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  deploy_to_production:
    name: Deploy Production
    runs-on: prod-runner
    if: github.event.ref == 'refs/heads/main'
    needs: deploy_to_staging
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
